### ISSUE TITLE
Maintenance Status

### ISSUE THREAD

**Issue by ProfLeao** [caseykneale/OpenSMILES.jl#23]
Hi everyone! What's the current maintenance status of this package? Does the owner (@caseykneale ) still reviewing the PRs?

Thanks!

**Comment by caseykneale** [comment]
Hi. I haven't been maintaining this package, the code quality is pretty rough, think I wrote it in a morning or something to hack on a different project.

I'll review a PR if you have one. If you'd like I could also make you a contributor. I don't believe in BDFL for code maintenance, if someone is compelled to work on this, don't let me slow you down. Only thing I ask is tests stay in place or evolve with the code base.

**Comment by ProfLeao** [comment]
Okay. Make me a contributor. One more thing: What exactly do you mean by “tests stay in place or evolve with the code base”?

**Comment by caseykneale** [comment]
Your wish is my command. You're now a contributor by your own free-will. 

Basically, don't delete tests unless the code changes, and if the code changes, the original tests should probably be in place :).

Let me know if you want second eyes on anything, have questions, or anything like that.  I am pretty reachable.

**Comment by ProfLeao** [comment]
Thank you very much. We have a lot of work in front of us and that's exciting.
